import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';
import { postData } from '../utils/apiCalls';

const Add: NextPage = () => {
  const [question, setQuestion] = useState<string>('');
  const [answer, setAnswer] = useState<string>('');
  const [stack, setStack] = useState<string>('');
  const [categories, setCategories] = useState<string[]>([]);
  const [category, setCategory] = useState<string>('');

  const addCategory = (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
    event.preventDefault();
    setCategories([...categories, category])
    setCategory('')
  }

  const postFlashCard = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    let response = await postData({
      question: question,
      answer: answer,
      side: stack,
      categories: categories
    })
    setQuestion('')
    setAnswer('')
    setStack('')
    setCategories([])
  }

  return (
    <>
      <Head>
        <title>ADDDDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form onSubmit={postFlashCard}>
          <h2>Add New Flash Card!</h2>

          <label htmlFor="question">Question:</label>
          <input
            type="text"
            id="question"
            value={question}
            onChange={(event)=> setQuestion(event.target.value)}
            required
          />

          <label htmlFor="answer">Answer:</label>
          <input
            type="text"
            id="answer"
            value={answer}
            onChange={(event)=> setAnswer(event.target.value)}
            required
          />

          <label htmlFor="stack">Engineering Stack:</label>
          <input
            type="text"
            id="stack"
            value={stack}
            onChange={(event)=> setStack(event.target.value)}
            required
          />

          <label htmlFor="category">Categories:</label>
          <input
            type="text"
            id="category"
            value={category}
            onChange={(event)=> setCategory(event.target.value)}
          />
          {categories}
          <button onClick={event=> addCategory(event)}>Add Category</button>
          
          <button type="submit">Submit</button>
        </form>
      </main>
    </>
  )
}

export default Add