import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Landing: NextPage = () => {
  return (
    <>
      <Head>
        <title>LANDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>
          blah blah blah
        </p>

        <Link href='/study'>
          <a>
            <button>Study</button>
          </a>
        </Link>

        <br></br><br></br>

        <Link href='/add'>
          <a>
            <button>Add</button>
          </a>
        </Link>
      </main>
    </>
  )
}

export default Landing