import type { NextPage } from 'next'
import Head from 'next/head'
import { getData } from '../utils/apiCalls'
import { CardType } from '../types'
import { InferGetStaticPropsType } from 'next'
import Link from 'next/link'
import Card from '../components/Card'

export const getStaticProps = async () => {
  const cards: CardType[] = await getData()

  if (!cards) {
    return {
      notFound: true,
    }
  }

  return {
    props: { cards },
  }
}

function Study({ cards }: InferGetStaticPropsType<typeof getStaticProps>) {
  let flashCards = cards.map(card => {
    return (
      <Link
        href={{
          pathname: `/article/${card.id}`,
          query: card,
        }}
        key={`${card.id}`}
      >
        <a>
          <Card key={`${card.id}`} card={card} />
        </a>
      </Link>
    )
  })

  return (
    <>
      <Head>
        <title>STUDDDDDDDDDDY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <p>
          Studies
        </p>
        {flashCards}
      </main>
    </>
  )
}

export default Study